version: "3.2"

services:
  db:
    image: postgres
    container_name: sms_bot_db
    volumes:
      - './development/server/postgres:/var/lib/postgresql'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - target: 5432
        published: 5447
        protocol: tcp
        mode: host