bot:
  username: 'username'
  token: 'token'
  proxy-enabled: false

proxy:
  host: 'host'
  port: port

spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5447/postgres'
    username: 'postgres'
    password: 'postgres'
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update